name: SpeedRoads
main: de.craftlancer.speedroads.SpeedRoads
version: ${project.version}
api-version: 1.19
author: Syd Montague
description: Meep Meep
commands:
  roads:
    description: Admin commands of SpeedRoads
    usage: /roads reload
permissions:
  speedroads.admin:
    description: Access to admin commands
    default: op